title: MapsIndoors SDK
email: support@mapsindoors.com
description: >- # this means to ignore newlines until "baseurl:"
  The documentation site for the MapsIndoors SDKs for iOS, Android and Web, as well as the Public Data API.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-octicons

exclude:
  - README.md
  - vendor
  - TODO

kramdown:
  # This is needed for the Table of Contents to work in Kramdown
  parse_block_html: true

# This is to ensure the permalinks below are displayed as /slug/, not /slug/index.html (e.g. https://mapsindoors.com/docs/ios/v3/set-up-your-enviroment).
permalink: pretty

collections_dir: collections

collections:
  ios:
    output: true
    permalink: :collection/:path
  cms:
    output: true
    permalink: :collection/:path
  android:
    output: true
    permalink: :collection/:path
  public-api:
    output: true
    permalink: :collection/:path
  web:
    output: true
    permalink: :collection/:path


defaults:
  -
    scope:
      path: "" # targets all files in the collection
    values:
      layout: "default"
  -
    scope:
      path: "_cms"
    values:
      platform: cms
  -
    scope:
      path: "_ios"
    values:
      platform: ios
  -
    scope:
      path: "_ios/v1"
    values:
      version: v1
      layout: tutorial
  -
    scope:
      path: "_ios/v2"
    values:
      version: v2
      layout: tutorial
  -
    scope:
      path: "_ios/v3"
    values:
      version: v3
      layout: tutorial
  -
    scope:
      path: "_android"
    values:
      platform: android
  -
    scope:
      path: "_android/v1"
    values:
      version: v1
      layout: tutorial
  -
    scope:
      path: "_android/v2"
    values:
      version: v2
      layout: tutorial
  -
    scope:
      path: "_android/v3"
    values:
      version: v3
      layout: tutorial
  -
    scope:
      path: "_public-api"
    values:
      platform: public-api
  -
    scope:
      path: "_public-api/v1"
    values:
      version: v1
      layout: tutorial
  -
    scope:
      path: "_web"
    values:
      platform: web
  -
    scope:
      path: "_web/v2"
    values:
      version: v2
      layout: tutorial
  -
    scope:
      path: "_web/v3"
    values:
      version: v3
      layout: tutorial
