title: MapsIndoors SDK
email: support@mapsindoors.com
description: >- # this means to ignore newlines until "baseurl:"
  The documentation site for the MapsIndoors SDKs for iOS, Android and Web, as well as the Public Data API.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-octicons

exclude:
  - README.md
  - vendor

# This is to ensure the permalinks below are displayed as /slug/, not /slug/index.html (e.g. https://mapsindoors.com/docs/ios/v3/set-up-your-enviroment).
permalink: pretty

collections_dir: collections

collections:
  ios:
    output: true
    permalink: :collection/:path

defaults:
  -
    scope:
      path: "" # targets all files in the collection
    values:
      layout: "default"
