# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: MapsIndoors SDK
# site.email
email: support@mapsindoors.com
# site.description
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# site.baseurl
baseurl: "" # the subpath of your site, e.g. /blog
# site.url
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site.github_username
github_username: mapsindoors

# Build settings
markdown: kramdown
plugins:
  - jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: "minima"

exclude:
  - README.md

# This is to ensure the permalinks below are displayed as /slug/, not /slug/index.html (e.g. https://mapsindoors.com/docs/ios/v3/set-up-your-enviroment).
permalink: pretty

collections_dir: collections

collections:
  ios:
    output: true
    # permalink: ios/:path/:name
    # sort_by: nav_weight # choose either this or order below
    # order:
    #  - hello-world.md
    #  - introduction.md
    #  - concepts/basics.md
    #  - concepts/advanced.md
