baseurl = "https://mapsindoors.github.io/"
languageCode = "en-us"
title = "MapsIndoors Developer"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-63919776-1"
publishDir = "docs"

[params]
	# General information
	author = "MapsPeople"
	description = "Everything you need to get started with MapsIndoors."
	copyright = "MapsIndoors &copy;2017"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/MapsIndoors/"

	version = "1.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "orange"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "MapsIndoors"
	email   = "support@mapspeople.com"


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
