name: Broken link check
on:
    push:
        branches:
            - feature/mhj/broken-link-checker

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1
        with:
          url: https://docs.mapsindoors.com
          cmd_params: "--one-page-only --color=always"  # Check just one page
