on:
    push:
        branches:
            - main

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
            TARGET: https://docs.mapsindoors.com
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            EXCLUDED_KEYWORDS: nuget, openid
            RECURSIVE: true
            RATE_LIMIT: 0
            TITLE: Broken link found to ${URL}
            ASSIGNEES: marksdk
