name: Markdown Lint
on: [push]

jobs:
  build:
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        runs-on: ubuntu-latest
        with:
          files: .
          config_file: ".markdownlint.json"
